blank_issues_enabled: false
contact_links:
  - name: "Precisa de ajuda?"
    url: "https://github.com/murlokfs/ifrn-projecthub/discussions"
    about: "Abra uma discussão se não souber qual template usar.",